
name: appstore_connect
description: Dart client for Apple App Store Connect API
version: 0.1.3
homepage: https://github.com/programmierbar/appstore_connect

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_jsonwebtoken: ^2.11.0
  intl: ^0.18.1
  http: ^1.1.0