
name: appstore_connect
description: Dart client for Apple App Store Connect API
version: 0.3.0
homepage: https://github.com/programmierbar/appstore_connect

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.14.0
  intl: ^0.19.0
  http: ^1.1.0